### ISSUE TITLE
Hexo管理工具

### ISSUE THREAD

**Issue by TonyChenn** [TonyChenn/TonyChenn.github.io#3]
https://tonychenn.cn/2019/08/14/Hexo%E7%AE%A1%E7%90%86%E5%B7%A5%E5%85%B7/

**Comment by 1756816846** [comment]
你好，链接失效了，能补一下吗

**Comment by 1756816846** [comment]
我的邮箱是1756816846@qq.com

**Comment by TonyChenn** [comment]
> 你好，链接失效了，能补一下吗
github地址在这里，https://github.com/TonyChenn/HexoBlogWriteTool.git

可运行直接下载：
[HexoWriteTool.zip](https://github.com/TonyChenn/TonyChenn.github.io/files/6915061/HexoWriteTool.zip)
